### ISSUE TITLE
404 for the manifest icon 

### ISSUE THREAD

**Issue by alrra** [webhintio/webhint.io#479]
https://webhint.io/static/images/manifest-icon.png  => 404 

Ref: https://github.com/webhintio/hint/issues/1220

**Comment by ststimac** [comment]
I don't think we ever created a manifest icon so one will need to be added.

**Comment by molant** [comment]
IIRC we were using the apple touch icon for this. Maybe we are not updating the Manifest content when the file gets optimized and cache busted.

**Comment by ststimac** [comment]
so not a design issue?

**Comment by molant** [comment]
@ststimac nope. I just merged the fix and waiting for deployment.

**Comment by alrra** [comment]
@molant The image issue is fixed, but now we have `"/static/site.webmanifest"`.

**Comment by Malvoz** [comment]
Now the image src is resolved as `/static/static/images/manifest-icon-a3d1c16640.png`

**Comment by Malvoz** [comment]
@molant 

https://github.com/webhintio/hint/issues/2496#issuecomment-495393546

> I believe we still have some issue with the manifest in webhint.io and one of the icons not existing anymore (or something like that).


Yeah the issue still persists. The issue is that the manifest file itself resides inside `/static/` but links (relatively) to `"src": "static/images/..."`, if `src` rather points to "/static/images/..." its should be good.

**Comment by molant** [comment]
Thanks @Malvoz, I fixed it via ec9b221f2c3697a04ac431e6a1a004c1cd8896e4
